name: ESLint

on:
  push:
    branches: [ 'main' ]
    paths: [ 'frontend/**' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  eslint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
  
    - name: Install dependencies
      working-directory: ./frontend/rubenpong
      run: npm install

    - name: Run eslint
      uses: sibiraj-s/action-eslint@v2
      with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          working-directory: ./frontend/rubenpong
          extensions: 'vue,js,jsx,cjs,mjs,ts,tsx,cts,mts'
          annotations: true
